// <auto-generated />
using MVCBasico_ReservaJuego.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCBasico_ReservaJuego.Migrations.ReservaDatabase
{
    [DbContext(typeof(ReservaDatabaseContext))]
    partial class ReservaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCBasico_ReservaJuego.Models.Cliente", b =>
                {
                    b.Property<int>("NroCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroCliente"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JuegoReservado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("NroCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MVCBasico_ReservaJuego.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<int>("IdJuego")
                        .HasColumnType("int");

                    b.Property<int>("NroCliente1")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("NroCliente1");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("MVCBasico_ReservaJuego.Models.Reserva", b =>
                {
                    b.HasOne("MVCBasico_ReservaJuego.Models.Cliente", "NroCliente")
                        .WithMany()
                        .HasForeignKey("NroCliente1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NroCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
